# Generated by Django 3.1.1 on 2020-09-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitefeeder',
            options={'verbose_name_plural': 'Сайты'},
        ),
        migrations.AddField(
            model_name='sitefeeder',
            name='feedscount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Парсить фидов'),
        ),
        migrations.AddField(
            model_name='sitefeeder',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='sitefeeder',
            name='scan_period',
            field=models.CharField(choices=[('SMALL_PERIOD', 'small period - 20 sec'), ('MIDDLE_PERIOD', 'middle period - 1min'), ('BIG_PERIOD', 'big period - 5 min')], default='MIDDLE_PERIOD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitefeeder',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitefeeder',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
