# Generated by Django 3.1.1 on 2020-09-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
        ('agprofile', '0002_agprofile_subscribe_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agprofile',
            name='subscribe_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.sitefeeder'),
        ),
    ]
