# Generated by Django 3.1.1 on 2020-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_auto_20200911_1634'),
        ('agprofile', '0004_auto_20200911_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agprofile',
            name='subscribe_to',
            field=models.ManyToManyField(null=True, to='feeder.SiteFeeder'),
        ),
    ]
