# Generated by Django 3.1.1 on 2020-09-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_auto_20200911_1634'),
        ('agprofile', '0005_auto_20200913_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agprofile',
            name='subscribe_to',
            field=models.ManyToManyField(blank=True, to='feeder.SiteFeeder'),
        ),
    ]
