# Generated by Django 3.1.1 on 2020-09-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('feed_url', models.URLField(blank=True, null=True)),
                ('feed_image_url', models.URLField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeder.sitefeeder')),
            ],
        ),
    ]
